#ASSEMBLER
#LABORATORIO 5
#FERNANDO HENGSTENBERG
#CARLOS CHEW

import struct


f = int('0100', 2)#NUMERO BINARIO ESCOGIDO AL AZAR, SOLO POR EJEMPLO
print ("BIN TO FLOAT")
print struct.unpack('f', struct.pack('I', f))[0]#IMPRIME EL RESULTADO DE LA CONVERSION DE BINARIO A PUNTO FLOTANTE





