#ASSEMBLER
#LABORATORIO 5
#FERNANDO HENGSTENBERG
#CARLOS CHEW

print ("CONVERTIDOR DE BINARIO FLOTANTE A DECIMAL")
#LA VARIBLE X GUARDA EL VALOR EN BINARIO

print ("INGRESE EL NUMERO BINARIO")
x = raw_input()
print int(str(x), 2)
